# Run configuration for PoC
# Values:
# subscriber.run.in.bg=true|false
# publisher.run.in.bg=true|false
# publisher.msg.limit=-1  # -1 means infinite (loop)
# publisher.msg.rate=10   # messages per second (optional)
# publisher.msg.interval.ms=500  # alternatively specify interval in ms
# start.media.driver=true|false  # whether to start media-driver from local aeron clone

subscriber.run.in.bg=true
publisher.run.in.bg=true
publisher.msg.limit=2000
publisher.msg.interval.ms=20
start.media.driver=true
